In [2]:
import pandas as pd

In [5]:
tumour = pd.read_csv('./data/sim_sact_tumour.csv', delimiter=',')

In [6]:
tumour

,MERGED_TUMOUR_ID,MERGED_PATIENT_ID,CONSULTANT_SPECIALITY_CODE,PRIMARY_DIAGNOSIS,MORPHOLOGY_CLEAN
0,10000001,10000235,101.0,C61,81403.0
1,10000002,10000315,101.0,C679,81403.0
2,10000003,10000337,100.0,C500,NaN
3,10000004,10000480,303.0,C829,NaN
4,10000005,10000533,823.0,D473,NaN
...,...,...,...,...,...
299722,220020152,220030400,370.0,C844,NaN
299723,220020159,220004252,823.0,C844,NaN
299724,220020175,220024703,800.0,C07,80203.0
299725,220020177,220038134,800.0,C859,81203.0
299726,220020183,220030424,370.0,C409,NaN